username_xpath = "//input[@name='username']"
password_xpath = "//input[@name='password']"
submit_btn = "//buttom[@type='submit']"
send_message_xpath = "//*[contains(text(),'Send message')]"
search_box_xpath = "/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div/div/div[1]/div/div[2]/div/div[2]"
search_input_xpath = "//input[@name='queryBox']"
user_username_xpath = "/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div/div/div[1]/div/div[3]/div/div/div[3]/div[1]/div/div/div[2]/div/div/div/span/span"
select_user_xpath = "/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div/div/div[1]/div/div[3]/div/div/div[1]/div[1]"
chat_btn_xpath = "//div[text()='Chat']"
message_box_xpath = "/html/body/div[2]/div/div/div[2]/div/div/div[1]/div[1]/div[2]/section/div/div/div/div[1]/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[2]"
message_box_xpath_enter = "/html/body/div[2]/div/div/div[2]/div/div/div[1]/div[1]/div[2]/section/div/div/div/div[1]/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div"
send_btn_xpath = "//*[contains(text(),'Send')]"
notif_btn = "/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[2]/div/div/div[3]/button[1]"
